### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by everettttt** [singer-io/tap-pendo#104]
Using Python 3.7 or 3.9 installed with `pyenv-win` on Windows 10.

Install the tap and target:

```sh
python -m venv tap-pendo
tap-pendo/Scripts/pip install tap-pendo  # tap-pendo/bin/pip on a Unix-like OS
python -m venv target-jsonl
tap-pendo/Scripts/pip install target-jsonl
```

Run in discover mode:

```sh
tap-pendo/Scripts/tap-pendo --config config.json --discover > catalog.json
```

Try sync mode:

```sh
tap-pendo/Scripts/tap-pendo --config config.json --catalog catalog.json | target-jsonl/Scripts/target-jsonl
```

But this error is thrown:

```
CRITICAL Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "path\to\tap-pendo\Scripts\tap-pendo-script.py", line 11, in <module>
    load_entry_point('tap-pendo==0.4.2', 'console_scripts', 'tap-pendo')()
  File "path\to\tap-pendo\lib\site-packages\singer\utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "path\to\tap-pendo\lib\site-packages\tap_pendo\__init__.py", line 158, in main
    args = utils.parse_args(REQUIRED_CONFIG_KEYS)
  File "path\to\tap-pendo\lib\site-packages\singer\utils.py", line 180, in parse_args
    args.catalog = Catalog.load(args.catalog)
  File "path\to\tap-pendo\lib\site-packages\singer\catalog.py", line 96, in load
    return Catalog.from_dict(json.load(fp))
  File "~\.pyenv\pyenv-win\versions\3.7.9\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "~\.pyenv\pyenv-win\versions\3.7.9\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "~\.pyenv\pyenv-win\versions\3.7.9\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "~\.pyenv\pyenv-win\versions\3.7.9\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

`config.json` definitely contains my `x_pendo_integration_key`. This doesn't seem to be caused by `pyenv`.

**Comment by everettttt** [comment]
Resolved. It's because I had `"include_anonymous_visitors": true` instead of `"include_anonymous_visitors": "true"` in `config.json`.
